GET http://localhost:8001/member/hello
Accept: application/json

<> 2023-07-29T122625.200.json

###

GET http://localhost:8000/member/hello
Accept: application/json

<> 2023-07-29T122625.200.json

###